# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Staging Slot'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MSDN'
    appType: 'webApp'
    WebAppName: 'testvulnappkmx2'
    ConfigurationSettings: '-httpsOnly true'
  enabled: true
